# Use the official Python image as the base image
FROM python:3.10-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . /app

ENTRYPOINT ["python3"]
CMD ["app.py"]